config/routes.rb
UrlShortener::Application.routes.draw do
  resources :short_urls


  resources :short_urls
  root :to => 'short_urls#new'
  get '/:id' => 'short_urls#redirect', as: "redirect"
end

app/models/short_url.rb
class ShortUrl < ActiveRecord::Base
  attr_accessible :key, :url
  validates_uniqueness_of :key
  validates_presence_of :key, :url

  def to_param
    self.key
  end

  def self.find(id)
    find_by_key(id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  # GET /short_urls
  # GET /short_urls.json
  def index
    @short_urls = ShortUrl.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @short_urls }
    end
  end

  # GET /short_urls/1
  # GET /short_urls/1.json
  def show
    @short_url = ShortUrl.find(params[:id])
    @url = redirect_url @short_url

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @short_url }
    end
  end

  # GET /short_urls/new
  # GET /short_urls/new.json
  def new
    @short_url = ShortUrl.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @short_url }
    end
  end

  def redirect
    @short_url = ShortUrl.find_by_key(params[:id])
    respond_to do |format|
      format.html { redirect_to @short_url.url } # show.html.erb
      format.json { render json: @short_url }
    end
  end

  # GET /short_urls/1/edit
  def edit
    @short_url = ShortUrl.find(params[:id])
  end

  # POST /short_urls
  # POST /short_urls.json
  def create
    @short_url = ShortUrl.new(params[:short_url])

    respond_to do |format|
      if @short_url.save
        format.html { redirect_to @short_url, notice: 'Short url was successfully created.' }
        format.json { render json: @short_url, status: :created, location: @short_url }
      else
        format.html { render action: "new" }
        format.json { render json: @short_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /short_urls/1
  # PUT /short_urls/1.json
  def update
    @short_url = ShortUrl.find(params[:id])

    respond_to do |format|
      if @short_url.update_attributes(params[:short_url])
        format.html { redirect_to @short_url, notice: 'Short url was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @short_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /short_urls/1
  # DELETE /short_urls/1.json
  def destroy
    @short_url = ShortUrl.find(params[:id])
    @short_url.destroy

    respond_to do |format|
      format.html { redirect_to short_urls_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_urls_helper.rb
module ShortUrlsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Url Shortener"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") UrlShortener
          .container.nav-collapse
            %ul.nav

    .container-fluid
      .span9
        = bootstrap_flash
        = yield
      %footer
        %p &copy; Jarmo Isotalo 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/short_urls/_form.html.haml
= form_for @short_url, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :url, :class => 'control-label'
    .controls
      = f.text_field :url, :class => 'text_field'
  .control-group
    = f.label :key, :class => 'control-label'
    .controls
      = f.text_field :key, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), short_urls_path, :class => 'btn'

app/views/short_urls/edit.html.haml
- model_class = ShortUrl
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/short_urls/index.html.haml
- model_class = ShortUrl
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:url)
      %th= model_class.human_attribute_name(:key)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @short_urls.each do |short_url|
      %tr
        %td= link_to short_url.id, short_url_path(short_url)
        %td= short_url.url
        %td= short_url.key
        %td=l short_url.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_short_url_path(short_url), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), short_url_path(short_url), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_short_url_path, :class => 'btn btn-primary'

app/views/short_urls/new.html.haml
- model_class = ShortUrl
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/short_urls/show.html.haml
- model_class = ShortUrl
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:url) + ':'
  %br
  = @short_url.url
%p
  %strong= model_class.human_attribute_name(:key) + ':'
  %br
  = @short_url.key

%p
  %strong This url will redirect you to your Url above
  %a{href: @url}
    =@url

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), short_urls_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_short_url_path(@short_url), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), short_url_path(@short_url), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'